// THE COMPOSER, END TO END, THROUGH THE UI.
//
// Three documents, generated by clicking the buttons a person clicks, and saved
// to disk so they can be read back. Invoking the generator directly would prove
// the generator works and nothing about whether the screen can drive it.
//
//   1. A full report for the client, over their markets and a chosen month.
//   2. The same report narrowed to one county.
//   3. A referral brief for a single project.
//
// The narrowed one must be SMALLER than the full one. That comparison is the
// whole test: two documents that differ only in a cover line, while claiming
// different scopes, would be the silent-omission failure the brief forbids.

import { test, expect } from '@playwright/test';
import path from 'node:path';
import { mkdirSync, writeFileSync, statSync } from 'node:fs';

const OUT = path.join('e2e', 'shots', 'documents');

async function download(page: import('@playwright/test').Page, testId: string, filename: string) {
  const wait = page.waitForEvent('download', { timeout: 120_000 });
  await page.getByTestId(testId).click();
  const dl = await wait;
  mkdirSync(OUT, { recursive: true });
  const dest = path.join(OUT, filename);
  await dl.saveAs(dest);
  return { dest, size: statSync(dest).size };
}

// Reading a count while the preview is rebuilding returns "--", which parses to
// zero and produces an assertion failure that looks like a broken filter. Every
// read waits for the rebuild to settle first.
async function counts(page: import('@playwright/test').Page) {
  await expect
    .poll(async () => await page.getByTestId('preview-projects-count').textContent(), { timeout: 60_000 })
    .not.toContain('--');
  const p = await page.getByTestId('preview-projects-count').textContent();
  const r = await page.getByTestId('preview-records-count').textContent();
  const pg = await page.getByTestId('preview-pages').textContent();
  const prov = await page.getByTestId('preview-provenance').textContent();
  return { p, r, pg, prov };
}

test('composer generates three documents', async ({ page }, testInfo) => {
  const mode = testInfo.project.name;
  const shot = (name: string) =>
    page.screenshot({ path: path.join('e2e', 'shots', mode, `10-${name}.png`), animations: 'disabled' });

  const summary: Record<string, unknown> = {};

  // ---- 1. THE FULL REPORT --------------------------------------------------
  await page.goto('/reports', { waitUntil: 'domcontentloaded' });
  await expect(page.getByTestId('report-client')).toBeVisible({ timeout: 120_000 });

  await page.getByTestId('report-client').selectOption({ label: 'Simtec Attractions' });
  await page.getByTestId('period-month').selectOption('m:2026-07');
  await expect(page.getByTestId('report-preview')).toBeVisible({ timeout: 60_000 });
  await expect
    .poll(async () => await page.getByTestId('preview-projects-count').textContent(), { timeout: 60_000 })
    .not.toContain('--');

  // Commentary, so the ASSESSMENT path is exercised in a real document rather
  // than only in the unit test.
  await page
    .locator('[data-commentary="headlines"]')
    .fill('Clark County filings are running ahead of Las Vegas this month. Worth a call before the next hearing cycle.');
  await page.evaluate(() => document.fonts.ready);

  const full = await counts(page);
  console.log(`FULL:     ${full.p} | ${full.r} | ${full.pg} | ${full.prov}`);
  summary.full = full;
  await shot('composer-full');

  const fullPdf = await download(page, 'gen-pdf', 'full-report.pdf');
  const fullCsv = await download(page, 'gen-csv', 'full-report.csv');
  const fullXlsx = await download(page, 'gen-xlsx', 'full-report.xlsx');
  console.log(`  pdf ${fullPdf.size} b, csv ${fullCsv.size} b, xlsx ${fullXlsx.size} b`);
  summary.fullFiles = { pdf: fullPdf.size, csv: fullCsv.size, xlsx: fullXlsx.size };

  const status = await page.getByTestId('generate-status').textContent();
  console.log(`  delivery: ${status}`);
  summary.deliveryStatus = status;

  // ---- 2. THE SAME REPORT, ONE COUNTY --------------------------------------
  await page.getByTestId('report-market').selectOption('Clark County');
  await expect
    .poll(async () => await page.getByTestId('preview-projects-count').textContent(), { timeout: 60_000 })
    .not.toBe(full.p);
  const narrowed = await counts(page);
  console.log(`NARROWED: ${narrowed.p} | ${narrowed.r} | ${narrowed.pg} | ${narrowed.prov}`);
  summary.narrowed = narrowed;

  const nFull = Number((full.p ?? '').replace(/\D/g, ''));
  const nNarrow = Number((narrowed.p ?? '').replace(/\D/g, ''));
  expect(nNarrow, 'narrowing to one county did not reduce the report').toBeLessThan(nFull);
  expect(nNarrow, 'the narrowed report is empty').toBeGreaterThan(0);

  await shot('composer-county');
  const countyPdf = await download(page, 'gen-pdf', 'county-report.pdf');
  console.log(`  pdf ${countyPdf.size} b`);
  summary.countyFiles = { pdf: countyPdf.size };

  // ---- 3. A REFERRAL BRIEF FOR ONE PROJECT ---------------------------------
  // Built from the composer: one project, the appendix on, and a title that says
  // what it is.
  await page.locator('input').first().fill('Referral brief');
  // ONE PROJECT, not a smaller market. The client stays selected: a referral is
  // still written for someone.
  const picker = page.getByTestId('report-project');
  const options = await picker.locator('option').all();
  const first = await options[1].getAttribute('value');
  await picker.selectOption(first ?? '');
  // Trim to the two sections a referral needs.
  for (const id of ['moved', 'markets', 'hearings', 'watchlist', 'coverage']) {
    const remove = page.locator(`[data-section="${id}"] button`);
    if (await remove.count()) await remove.click();
  }
  const addAppendix = page.locator('[data-add-section="appendix"]');
  if (await addAppendix.count()) await addAppendix.click();
  await page
    .locator('[data-commentary="headlines"]')
    .fill('Referred for introduction. The applicant is active across two markets and the filing pattern suggests a decision inside the quarter.');
  await expect(page.getByTestId('report-preview')).toBeVisible();
  await page.evaluate(() => document.fonts.ready);

  const referral = await counts(page);
  console.log(`REFERRAL: ${referral.p} | ${referral.r} | ${referral.pg} | ${referral.prov}`);
  summary.referral = referral;
  await shot('composer-referral');
  const refPdf = await download(page, 'gen-pdf', 'referral-brief.pdf');
  console.log(`  pdf ${refPdf.size} b`);
  summary.referralFiles = { pdf: refPdf.size };

  mkdirSync(OUT, { recursive: true });
  writeFileSync(path.join(OUT, 'summary.json'), JSON.stringify(summary, null, 2));
});
