// THE COMPOSER, END TO END, THROUGH THE UI.
//
// Three documents, generated by clicking the buttons a person clicks, and saved
// to disk so they can be read back. Invoking the generator directly would prove
// the generator works and nothing about whether the screen can drive it.
//
//   1. A full report for the client, over their markets and a chosen month.
//   2. The same report narrowed to one county.
//   3. A referral brief for a single project.
//
// The narrowed one must be SMALLER than the full one. That comparison is the
// whole test: two documents that differ only in a cover line, while claiming
// different scopes, would be the silent-omission failure the brief forbids.
//
// THIS HARNESS DOES NOT WRITE THE ASSESSMENTS.
//
// It used to. It typed "Clark County filings are running ahead of Las Vegas
// this month" into the commentary box, and that sentence was rendered as
// [ASSESSMENT], under Philip's brand, in a PDF that then went out. Nobody
// checked whether it was true, because nobody wrote it: a fixture invented a
// market judgement and the provenance system faithfully attributed it to him.
//
// The provenance rule is about who said a thing, and a test fixture is not a
// person. So the commentary boxes are left empty and the documents carry no
// assessment except the ones the generator produces about its own coverage -
// the scoping statement and the coverage note, which are statements about this
// document rather than about the market. The ASSESSMENT path stays covered by
// those, and the tally below asserts it.

import { test, expect } from '@playwright/test';
import { REFERRAL_SECTION_IDS } from '../lib/report-sections';
import path from 'node:path';
import { mkdirSync, writeFileSync, statSync } from 'node:fs';

const OUT = path.join('e2e', 'shots', 'documents');

async function download(page: import('@playwright/test').Page, testId: string, filename: string) {
  await assertNoInventedAssessments(page);
  const wait = page.waitForEvent('download', { timeout: 120_000 });
  await page.getByTestId(testId).click();
  const dl = await wait;
  mkdirSync(OUT, { recursive: true });
  const dest = path.join(OUT, filename);
  // ---- ONEDRIVE HOLDS THE FILE IT IS SYNCING --------------------------------
  //
  // saveAs copies onto a path inside the repo, and this repo lives in OneDrive,
  // which takes a handle on a file the moment it changes. The copy then fails
  // with EBUSY - not always, and not on the same document twice - and the run
  // goes red on the one thing in it that is nothing to do with the product.
  // Same root cause as the .next EBUSY the CLAUDE.md run note already warns
  // about, one directory over.
  //
  // A FLAKY GATE IS A GATE NOBODY BELIEVES, and that is the real cost: a suite
  // that fails for environmental reasons is a suite whose next real failure gets
  // waved through. So the write is retried on EBUSY and EPERM only - a genuinely
  // missing download or a bad path still fails immediately, first time - and the
  // retries are reported, because a document that took four attempts to write is
  // worth knowing about even when it succeeds.
  let lastError: unknown;
  for (let attempt = 1; attempt <= 5; attempt++) {
    try {
      await dl.saveAs(dest);
      if (attempt > 1) console.log(`  ${filename} written on attempt ${attempt} (OneDrive held it)`);
      return { dest, size: statSync(dest).size };
    } catch (e) {
      const code = (e as { code?: string })?.code ?? '';
      const locked = /EBUSY|EPERM/.test(code) || /EBUSY|EPERM/.test(String(e));
      if (!locked) throw e;
      lastError = e;
      await new Promise((r) => setTimeout(r, attempt * 750));
    }
  }
  throw new Error(
    `${filename} could not be written after 5 attempts; OneDrive held the file. Last error: ${String(lastError).slice(0, 200)}`
  );
}

// THE GUARD. Every commentary box must be empty at the moment a document is
// generated, so a future edit cannot quietly reintroduce a fixture-written
// assessment into a client-facing PDF.
async function assertNoInventedAssessments(page: import('@playwright/test').Page) {
  const typed = await page
    .locator('[data-commentary]')
    .evaluateAll((els) =>
      els
        .map((e) => ({ id: e.getAttribute('data-commentary'), v: (e as HTMLTextAreaElement).value.trim() }))
        .filter((x) => x.v.length > 0)
    );
  expect(typed, 'this harness wrote an assessment into a client document').toEqual([]);
}

// Reading a count while the preview is rebuilding returns "--", which parses to
// zero and produces an assertion failure that looks like a broken filter. Every
// read waits for the rebuild to settle first.
async function counts(page: import('@playwright/test').Page) {
  await expect
    .poll(async () => await page.getByTestId('preview-projects-count').textContent(), { timeout: 60_000 })
    .not.toContain('--');
  const p = await page.getByTestId('preview-projects-count').textContent();
  const r = await page.getByTestId('preview-records-count').textContent();
  const pg = await page.getByTestId('preview-pages').textContent();
  const prov = await page.getByTestId('preview-provenance').textContent();
  return { p, r, pg, prov };
}

test('composer generates three documents', async ({ page }, testInfo) => {
  const mode = testInfo.project.name;
  const shot = (name: string) =>
    page.screenshot({ path: path.join('e2e', 'shots', mode, `10-${name}.png`), animations: 'disabled' });

  const summary: Record<string, unknown> = {};

  // ---- 1. THE FULL REPORT --------------------------------------------------
  await page.goto('/reports', { waitUntil: 'domcontentloaded' });
  await expect(page.getByTestId('report-client')).toBeVisible({ timeout: 120_000 });

  await page.getByTestId('report-client').selectOption({ label: 'Simtec Attractions' });
  await page.getByTestId('period-month').selectOption('m:2026-07');
  await expect(page.getByTestId('report-preview')).toBeVisible({ timeout: 60_000 });
  await expect
    .poll(async () => await page.getByTestId('preview-projects-count').textContent(), { timeout: 60_000 })
    .not.toContain('--');

  await page.evaluate(() => document.fonts.ready);

  const full = await counts(page);
  console.log(`FULL:     ${full.p} | ${full.r} | ${full.pg} | ${full.prov}`);
  summary.full = full;
  await shot('composer-full');

  const fullPdf = await download(page, 'gen-pdf', 'full-report.pdf');
  const fullCsv = await download(page, 'gen-csv', 'full-report.csv');
  const fullXlsx = await download(page, 'gen-xlsx', 'full-report.xlsx');
  console.log(`  pdf ${fullPdf.size} b, csv ${fullCsv.size} b, xlsx ${fullXlsx.size} b`);
  summary.fullFiles = { pdf: fullPdf.size, csv: fullCsv.size, xlsx: fullXlsx.size };

  // ---- 1b. THE SAME SCOPE AT 15 AND AT 30 ----------------------------------
  //
  // The detail cap is the one control whose right value cannot be reasoned out
  // in advance: it trades page count against coverage, and what reads well
  // depends on what an entry costs on the page. The July standard ran 26 pages
  // and detailed considerably more than the default of 15. So both are
  // generated and saved, to be read side by side. Neither is asserted to be
  // correct; the comparison is the deliverable.
  //
  // ON THE INTERNAL SCOPE, NOT ON SIMTEC'S. This first ran against the client
  // selected above and produced two identical documents, because Simtec's
  // stored scope resolves to 13 projects and a cap of 15 never binds on 13. The
  // assertion caught it, which is the reason it is written as a comparison of
  // page counts rather than as a screenshot. Selection only means anything
  // where there is more in scope than fits, so the comparison uses the whole
  // register: no client, every market.
  await page.getByTestId('report-client').selectOption({ label: 'No client (internal)' });
  await expect
    .poll(async () => await page.getByTestId('preview-projects-count').textContent(), { timeout: 60_000 })
    .not.toContain('--');

  const at15 = await counts(page);
  console.log(`INTERNAL 15: ${at15.p} | ${at15.r} | ${at15.pg} | ${at15.prov}`);
  summary.detail15 = at15;
  await shot('composer-detail-15');
  const pdf15 = await download(page, 'gen-pdf', 'register-detail-15.pdf');
  const csv15 = await download(page, 'gen-csv', 'register-detail-15.csv');
  console.log(`  pdf ${pdf15.size} b, csv ${csv15.size} b`);

  await page.getByTestId('report-detail-cap').fill('30');
  await expect
    .poll(async () => await page.getByTestId('preview-pages').textContent(), { timeout: 60_000 })
    .not.toBe(at15.pg);
  const at30 = await counts(page);
  console.log(`INTERNAL 30: ${at30.p} | ${at30.r} | ${at30.pg} | ${at30.prov}`);
  summary.detail30 = at30;
  await shot('composer-detail-30');
  const pdf30 = await download(page, 'gen-pdf', 'register-detail-30.pdf');
  const csv30 = await download(page, 'gen-csv', 'register-detail-30.csv');
  console.log(`  pdf ${pdf30.size} b, csv ${csv30.size} b`);
  summary.detailFiles = { at15: pdf15.size, at30: pdf30.size };

  // A document detailing 30 must be longer than one detailing 15, or the cap
  // is not doing anything and the two files differ only in a cover line.
  expect(
    Number((at30.pg ?? '').replace(/\D/g, '')),
    'raising the detail cap did not lengthen the document'
  ).toBeGreaterThan(Number((at15.pg ?? '').replace(/\D/g, '')));

  // Back to the client and the default for everything that follows, so the
  // county comparison below measures geography rather than detail.
  await page.getByTestId('report-detail-cap').fill('15');
  await page.getByTestId('report-client').selectOption({ label: 'Simtec Attractions' });
  await expect
    .poll(async () => await page.getByTestId('preview-projects-count').textContent(), { timeout: 60_000 })
    .toBe(full.p);

  const status = await page.getByTestId('generate-status').textContent();
  console.log(`  delivery: ${status}`);
  summary.deliveryStatus = status;

  // ---- 2. THE SAME REPORT, ONE COUNTY --------------------------------------
  // GEOGRAPHY IS CHIPS NOW, NOT A SELECT. The composer used to offer one
  // market through a dropdown, which could express "narrow to Clark County"
  // and could not express "New York City plus Las Vegas plus San Antonio" -
  // three markets in three states, which is what a client scope holding
  // sixteen markets actually needs. Clicking the chip is the same narrowing
  // this test always asserted; only the control changed.
  await page
    .locator('[data-testid="report-market-chips"] [data-report-option="Clark County"]')
    .click();
  await expect
    .poll(async () => await page.getByTestId('preview-projects-count').textContent(), { timeout: 60_000 })
    .not.toBe(full.p);
  const narrowed = await counts(page);
  console.log(`NARROWED: ${narrowed.p} | ${narrowed.r} | ${narrowed.pg} | ${narrowed.prov}`);
  summary.narrowed = narrowed;

  const nFull = Number((full.p ?? '').replace(/\D/g, ''));
  const nNarrow = Number((narrowed.p ?? '').replace(/\D/g, ''));
  expect(nNarrow, 'narrowing to one county did not reduce the report').toBeLessThan(nFull);
  expect(nNarrow, 'the narrowed report is empty').toBeGreaterThan(0);

  await shot('composer-county');
  const countyPdf = await download(page, 'gen-pdf', 'county-report.pdf');
  console.log(`  pdf ${countyPdf.size} b`);
  summary.countyFiles = { pdf: countyPdf.size };

  // ---- 3. A REFERRAL BRIEF FOR ONE PROJECT ---------------------------------
  // Built from the composer: one project, the appendix on, and a title that says
  // what it is.
  await page.locator('input').first().fill('Referral brief');
  // ONE PROJECT, not a smaller market. The client stays selected: a referral is
  // still written for someone.
  //
  // THE PROJECT IS CHOSEN, NOT TAKEN. This used to grab options[1] and hope.
  // After the August capture that project had no filing inside the period, so
  // the composer correctly refused to generate - 1 project and 0 records is the
  // self-contradictory basis the brief forbids - and the harness failed on a
  // disabled button, which reads like a broken control rather than a working
  // guard. A referral brief needs a project with something to cite, so the
  // harness looks for one.
  const picker = page.getByTestId('report-project');
  const options = await picker.locator('option').all();
  let chosen: string | null = null;
  for (const option of options.slice(1, 12)) {
    const value = await option.getAttribute('value');
    if (!value) continue;
    await picker.selectOption(value);
    await expect
      .poll(async () => await page.getByTestId('preview-records-count').textContent(), { timeout: 60_000 })
      .not.toContain('--');
    const recs = Number(
      ((await page.getByTestId('preview-records-count').textContent()) ?? '').replace(/\D/g, '')
    );
    if (recs > 0) {
      chosen = value;
      console.log(`  referral project: ${(await option.textContent())?.trim()} (${recs} records)`);
      break;
    }
  }
  expect(chosen, 'no project in this scope has a filing in the period to write a brief about').not.toBeNull();
  // ---- AND IT IS BUILT FROM THE REFERRAL SECTION SET ------------------------
  //
  // THE FILE CALLED referral-brief.pdf WAS NOT A REFERRAL BRIEF. This block used
  // to delete the market sections from the DEFAULT set and add the appendix, so
  // the artefact this harness produced, named as a brief and read back as one,
  // contained the market report's cover, its headline list and its appendix and
  // not one of referral-project, referral-people, referral-conditions or
  // referral-press. Every referral defect in the shipped brief was invisible
  // here by construction, because the document being photographed was a
  // different document from the one the button generates.
  //
  // Same shape as the golden case a-read-back-tool-builds-the-clients-document.
  // A verification tool that builds a different document from the one it
  // verifies is worse than no tool, because it reports green.
  for (const id of ['cover', 'moved', 'headlines', 'categories', 'hearings', 'watchlist', 'coverage']) {
    const remove = page.locator(`[data-section="${id}"] button`);
    if (await remove.count()) await remove.click();
  }
  //
  // AND THE LIST IS READ FROM REFERRAL_SECTION_IDS, NOT TYPED OUT HERE.
  //
  // It WAS typed out, directly under the paragraph above explaining why a
  // harness that builds a different document from the button is worse than no
  // harness. Adding referral-coverage to the section set left this list at five
  // and the photographed brief went on having no coverage note - the same defect
  // in the same file, one paragraph below its own description of it. A hardcoded
  // copy of a list is a copy that goes stale.
  for (const id of REFERRAL_SECTION_IDS) {
    const add = page.locator(`[data-add-section="${id}"]`);
    expect(await add.count(), `the composer offers no ${id} section to add`).toBeGreaterThan(0);
    await add.click();
  }
  // The document must actually contain them, or the clicks did nothing and the
  // brief is silently a market report again.
  const built = await page
    .locator('[data-section]')
    .evaluateAll((els) => els.map((e) => e.getAttribute('data-section')));
  expect(built, 'the referral brief was not built from the referral section set').toEqual(
    REFERRAL_SECTION_IDS
  );
  // No commentary. A referral brief without Philip's read is a thin document,
  // and the composer says so on screen; a thin document is still better than
  // one carrying a judgement he never made.
  await expect(page.getByTestId('report-preview')).toBeVisible();
  await page.evaluate(() => document.fonts.ready);

  const referral = await counts(page);
  console.log(`REFERRAL: ${referral.p} | ${referral.r} | ${referral.pg} | ${referral.prov}`);
  summary.referral = referral;
  await shot('composer-referral');
  const refPdf = await download(page, 'gen-pdf', 'referral-brief.pdf');
  console.log(`  pdf ${refPdf.size} b`);
  summary.referralFiles = { pdf: refPdf.size };

  mkdirSync(OUT, { recursive: true });
  writeFileSync(path.join(OUT, 'summary.json'), JSON.stringify(summary, null, 2));
});
