// THE MONDAY DOCUMENT. Brief U item 5, steps 7 and 10.
//
//   CADENCE_RUN=1 npx playwright test --project=deliver
//
// One PDF per due client, generated by driving the buttons a person drives, and
// written where the workflow can upload it. Skipped unless CADENCE_RUN is set,
// so a local gate run reports it as SKIPPED rather than mailing anybody.
//
// ---------------------------------------------------------------------------
// WHY PLAYWRIGHT AND NOT A GENERATOR
// ---------------------------------------------------------------------------
//
// buildReport is behind 'use client' in app/(app)/reports/page.tsx, so the only
// thing in this repository that produces a document without a person is the
// composer harness. Extracting the builder into a headless path is real work
// that has to respect the package split, which is asymmetric and has broken a
// deploy once already.
//
// So the first Monday document is built by the exact code path Philip uses,
// which is also the only way to be sure it is the same document. That is a
// deliberate first version and not the right long-term answer, and it is
// written down here so the next person does not mistake one for the other.
//
// ---------------------------------------------------------------------------
// IT DOES NOT DECIDE WHO IS DUE AND IT DOES NOT ADVANCE ANYTHING
// ---------------------------------------------------------------------------
//
// `npm run cadence:due` decides and writes cadence/due.json; this reads it.
// `npm run cadence:record` advances next_delivery and runs AFTER this, from
// cadence/delivered.json, because a next_delivery advanced before the generation
// is a week silently skipped when the generation fails.
//
// The delivery row itself is written by /api/report on download, as it already
// was for every document a person has generated. Nothing new records it here.

import { test, expect } from '@playwright/test';
import path from 'node:path';
import { mkdirSync, writeFileSync, readFileSync, existsSync, statSync } from 'node:fs';

// The cadence directory is at the REPO ROOT, one level above dashboard/, which
// is where Playwright runs from.
const ROOT = path.join('..');
const DUE_FILE = path.join(ROOT, 'cadence', 'due.json');
const DELIVERED_FILE = path.join(ROOT, 'cadence', 'delivered.json');
const OUT_DIR = path.join(ROOT, 'cadence', 'documents');

interface DueClient {
  id: string;
  name: string;
  cadence: string | null;
  next_delivery: string | null;
  included: number;
}

const slug = (s: string): string =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

test('the weekly document, one per due client', async ({ page }) => {
  test.skip(
    process.env.CADENCE_RUN !== '1',
    'CADENCE_RUN is not set: this generates client documents and only the weekly workflow should.'
  );
  test.setTimeout(900_000);

  expect(existsSync(DUE_FILE), `${DUE_FILE} does not exist. Run cadence:due first.`).toBe(true);
  const due = JSON.parse(readFileSync(DUE_FILE, 'utf8')) as DueClient[];
  console.log(`\n===== THE WEEKLY DOCUMENT =====`);
  console.log(`due clients: ${due.length}`);

  mkdirSync(OUT_DIR, { recursive: true });
  const delivered: { clientId: string; name: string; file: string; bytes: number; projects: string; records: string }[] = [];

  for (const client of due) {
    console.log(`\n--- ${client.name} (${client.included} included projects) ---`);

    // THE PERIOD IS SEVEN DAYS, SET THROUGH THE URL. The reports screen hides
    // the rolling chips (showRolling={false}), but the period is a query
    // parameter that usePeriodState reads, so a weekly window needs no new
    // control. 'this-week' would be wrong on a Monday 01:00 run: the week is an
    // hour old and the document would cover an hour.
    await page.goto('/reports?period=7d', { waitUntil: 'domcontentloaded' });
    await expect(page.getByTestId('report-client')).toBeVisible({ timeout: 120_000 });
    await page.getByTestId('report-client').selectOption({ label: client.name });

    await expect(page.getByTestId('report-preview')).toBeVisible({ timeout: 120_000 });
    await expect
      .poll(async () => await page.getByTestId('preview-projects-count').textContent(), { timeout: 120_000 })
      .not.toContain('--');

    const projects = (await page.getByTestId('preview-projects-count').textContent())?.trim() ?? '?';
    const records = (await page.getByTestId('preview-records-count').textContent())?.trim() ?? '?';
    console.log(`  preview: ${projects} projects, ${records} records`);

    // ---- A ZERO WEEK STILL SENDS THE DOCUMENT -----------------------------
    //
    // BRIEF-S-ITEM-5-CADENCE section 4, and it is a decision rather than an
    // oversight. Silence is indistinguishable from the system being dead, which
    // is exactly what standing rule 3 exists to prevent: if a quiet week and a
    // broken pipeline produce the same empty inbox, the client cannot tell which
    // one they are paying for. The document carries the scope, the period, the
    // explicit count, every market read with its last capture date, and anything
    // withheld with its reason. That is the cheapest possible proof the system
    // ran, and it is a feature of the product.
    //
    // The one case where nothing is generated is a REFUSAL by the composer
    // itself - an incomplete provenance basis - and that is the gate doing its
    // job. It is reported rather than swallowed.
    const blocked = await page.getByTestId('basis-refusal').count();
    if (blocked > 0) {
      const why = (await page.getByTestId('basis-refusal').textContent())?.trim() ?? '(no reason given)';
      console.log(`  REFUSED by the composer: ${why}`);
      continue;
    }

    const filename = `${slug(client.name)}-weekly-${new Date().toISOString().slice(0, 10)}.pdf`;
    const wait = page.waitForEvent('download', { timeout: 180_000 });
    await page.getByTestId('gen-pdf').click();
    const dl = await wait;
    const dest = path.join(OUT_DIR, filename);
    await dl.saveAs(dest);
    const bytes = statSync(dest).size;

    // READ IT BACK OFF DISK. Standing rule 11: a generator that PRINTS an
    // artefact reads it back, so a missing file fails the run instead of
    // manufacturing the appearance of one.
    expect(bytes, `${filename} was written empty`).toBeGreaterThan(1000);
    const head = readFileSync(dest).subarray(0, 5).toString('latin1');
    expect(head, `${filename} is not a PDF`).toBe('%PDF-');
    console.log(`  wrote ${dest} (${bytes} b)`);

    delivered.push({ clientId: client.id, name: client.name, file: filename, bytes, projects, records });
  }

  writeFileSync(DELIVERED_FILE, JSON.stringify(delivered, null, 1));
  console.log(`\nwrote ${DELIVERED_FILE}: ${delivered.length} of ${due.length} due clients delivered`);

  // A DUE CLIENT THAT PRODUCED NO DOCUMENT FAILS THE JOB. Not silently skipped:
  // the whole point of the cadence is that a week with nothing to report still
  // sends something, so a due client with no file is a fault and not a quiet
  // week.
  expect(
    delivered.length,
    `${due.length - delivered.length} due client(s) produced no document. A quiet week still sends the document.`
  ).toBe(due.length);
});
